MLT-651
zimmerman-zimmerman/IATI-Humanitarian-Data-Portal-CMS pull request #31
Opened 2019-11-08 11:17 UTC by luminhan-zz

https://zimmermanzimmerman.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=MLT&modal=detail&selectedIssue=MLT-651&assignee=5ce283a0f433c20ff1130508

2019-11-08 13:21 UTC, juanalb approved these changes
changed relative imports to absolute

2019-11-08 15:28 UTC, Martizs requested changes
1) Why does the text say that the date needs to be today or later?
2) And please change the date input format to be the same as in the table. Meaning YYYY/mm/dd . 
3) Please add in the columns and input fields for 'Providing more granular v2.03 data' & 'Publishing IATI traceability information'. Because the main idea is to input a fixed date of today, with currently calculated values. Which means we will have values for v203 data and for traceability.

2019-11-13 12:24 UTC, Martizs approved these changes

2019-11-13 13:05 UTC, merged

2020-04-06 10:43 UTC, zz-github-machine commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/zimmerman-zimmerman/IATI-Humanitarian-Data-Portal-CMS/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: